Algorítmo do Método Gaussiano de Solução de Matrizes(Exemplo 1): 

In [0]:
import numpy as np

m=4
n=4

matriz=np.array([[1, -1, 0, 5],[3, -2, 1, -1],[1, 1, 9, 4],[1, -7, 2, 3]])
vetor=np.array([18, 8, 47, 32])
x=np.array([0, 0, 0, 0])

print ('Matriz dada:')
print(matriz)

type(m)
for k in range(m):
  for r in range(k+1,m):
    f=(matriz[r,k]/matriz[k,k])
    vetor[r]=vetor[r]-(f*vetor[k])
    for c in range(0,n):
      matriz[r,c]=matriz[r,c]-(f*matriz[k,c])

#substituição para trás

x[m-1]=vetor[m-1]/matriz[m-1,m-1]

for r in range(m-2,-1,-1):
  suma=0
  for c in range(0,n):
    suma=suma+matriz[r,c]*x[c]
  x[r]=(vetor[r]-suma)/matriz[r,r]


print ('\nA Matriz triangular superior:')

print(matriz)

print ('\nO Vetor solução:')

print(vetor)

print ('\nResultados da resolução do sistema linear: ')

print(x)

Matriz dada:
[[ 1 -1  0  5]
 [ 3 -2  1 -1]
 [ 1  1  9  4]
 [ 1 -7  2  3]]

A Matriz triangular superior:
[[   1   -1    0    5]
 [   0    1    1  -16]
 [   0    0    7   31]
 [   0    0    0 -133]]

O Vetor solução:
[  18  -46  121 -400]

Resultados da resolução do sistema linear: 
[ 1 -2  4  3]


Algorítmo do Método Gaussiano de Solução de Matrizes(Exemplo 2): 

In [0]:
import numpy as np

m=3
n=3

matriz=np.array([[1, 1, 1],[2, 3, 5],[1, 1, 2]], dtype = 'f')
vetor=np.array([400, 1500, 600], dtype = 'f')
x=np.array([0, 0, 0], dtype = 'f')

print ('Matriz dada:')
print(matriz)

type(m)
for k in range(m):
  for r in range(k+1,m):
    f=(matriz[r,k]/matriz[k,k])
    vetor[r]=vetor[r]-(f*vetor[k])
    for c in range(0,n):
      matriz[r,c]=matriz[r,c]-(f*matriz[k,c])

#substituição para trás

x[m-1]=vetor[m-1]/matriz[m-1,m-1]

for r in range(m-2,-1,-1):
  suma=0
  for c in range(0,n):
    suma=suma+matriz[r,c]*x[c]
  x[r]=(vetor[r]-suma)/matriz[r,r]


print ('\nA Matriz triangular superior:')

print(matriz)

print ('\nO Vetor solução:')

print(vetor)

print ('\nResultados da resolução do sistema linear: ')

print(x)

Matriz dada:
[[1. 1. 1.]
 [2. 3. 5.]
 [1. 1. 2.]]

A Matriz triangular superior:
[[1. 1. 1.]
 [0. 1. 3.]
 [0. 0. 1.]]

O Vetor solução:
[400. 700. 200.]

Resultados da resolução do sistema linear: 
[100. 100. 200.]


Tentativa SIMPLEX - 

In [0]:
import numpy as np